openapi: 3.0.0

info:
  version: 0.0.1-alpha
  title: Marvel Characters Service
  description: The Marvel Characters service

tags:
  - name: "Marvel Characters API"

servers:
  - url: http://localhost:8080
    description: API for local development

paths:

  /characters:
    get:
      summary: Retrieve a list of Marvel characters
      description: Returns a list of Marvel characters stored from 'http://developer.marvel.com'
      operationId: getAllCharacters
      tags:
        - "Marvel Characters API"
      responses:
        "200":
          description: A list of character ids are returned
          content:
            application/json:
              schema:
                type: array
                items:
                  type: integer

  /characters/{id}:
    get:
      summary: Retrieve a specific Marvel character
      description: Returns a specified Marvel character in realtime from 'http://developer.marvel.com'
      operationId: getOneCharacter
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            minimum: 1
          description: The Marvel Character ID
      responses:
        "200":
          description: A list of character ids are returned
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Character'

components:
  schemas:
    Character:
      description: This represents a reduced version of the Marvel Character
      type: object
      properties:
        id:
          description: Marvel's unique identifier for the character
          type: integer
        name:
          description: The name of the character
          type: string
        description:
          description: A brief description of the character
          type: string
        thumbnail:
          description: A reference to the image of the character
          type: object
          properties:
            path:
              description: The URI of the image
              type: string
            extension:
              description: The file type extention of the image URI
              type: string